#
# Consul
#
# https://hub.docker.com/r/progrium/consul/
# https://www.consul.io/docs/
#
consul:
  image: progrium/consul
  command: -server -bootstrap -ui-dir /ui
  ports:
    - "8400:8400"
    - "8500:8500"
    - "8600:8600/udp"

#
# Nomad
#
# https://nomadproject.io/docs/
#
nomad:
  build: nomad
  privileged: true
  command: agent -dev
  ports:
    - "4646:4646"
    - "4647:4647"
    - "4648:4648"
  volumes:
    - /run/docker.sock:/run/docker.sock
  links:
    - consul

#
# Traefik
#
# https://hub.docker.com/r/emilevauge/traefik/
# https://github.com/EmileVauge/traefik/blob/master/docs/index.md
#
traefik:
  image: emilevauge/traefik
  ports:
    - "8080:8080"
    - "80:80"
  volumes:
    - "./traefik/traefik.toml:/traefik.toml"
  links:
    - consul
